name: Build EXE

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      APP_NAME: MyApp
      ENTRYPOINT: main.py

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if (Test-Path "requirements.txt") { pip install -r requirements.txt }
          pip install pyinstaller

      - name: Build executable
        run: |
          $icon = ""
          if (Test-Path "generated-icon.png") { $icon = "--icon generated-icon.png" }

          $add = ""
          if (Test-Path "templates") { $add = "--add-data templates;templates" }

          pyinstaller $icon $add --name "$env:APP_NAME" --onefile --windowed "$env:ENTRYPOINT"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-Windows
          path: dist/${{ env.APP_NAME }}.exe
